name: 'Benchmarkdotnet Results Publisher'
description: 'Publishes results from BenchmarkDotNet benchmarks to a GitHub repository.'
author: 'Martin Costello'
branding:
  icon: 'trending-down'
  color: 'green'
inputs:
  branch:
    description: 'The optional Git branch to push the results to.'
    required: false
  commit-message:
    description: 'The optional Git commit message to use.'
    required: false
  fail-on-threshold:
    description: 'If true, will cause the workflow to fail if either the duration or memory threshold is exceeded.'
    required: false
    default: false
  fail-threshold-duration:
    description: 'The optional threshold, as a ratio, which determines if the current workflow fails based on the previous result for a duration metric.'
    required: false
  fail-threshold-memory:
    description: 'The optional threshold, as a ratio, which determines if the current workflow fails based on the previous result for a memory usage metric.'
    required: false
  max-items:
    description: 'The optional maximum number of results to include for each suite of benchmark results.'
    required: false
  name:
    description: 'The optional name to use to group the benchmark results that are found into suites.'
    required: false
  output-file-path:
    description: 'The optional path of the file to write the results to.'
    required: false
  output-step-summary:
    description: 'If true, will output the Markdown results from BenchmarkDotNet to GITHUB_STEP_SUMMARY.'
    required: false
    default: true
  repo:
    description: 'The optional GitHub repository to push the results to.'
    required: false
    default: ${{ github.repository }}
  repo-token:
    description: 'The GitHub access token to use to push the results to a GitHub repository.'
    required: false
    default: ${{ github.token }}
  results-path:
    description: 'The optional path of the BenchmarkDotNet results directory to process.'
    required: false
runs:
  using: 'node20'
  main: 'dist/main.js'
